/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Data Transfer Object for Apparel entities
 */
export type ApparelDto = {
    /**
     * Unique identifier for the apparel. Read-only field generated by the system.
     */
    readonly id?: number;
    /**
     * Version number for optimistic locking. Read-only field incremented on each update.
     */
    readonly version?: number;
    /**
     * Date and time when the apparel was created. Read-only field.
     */
    readonly createdDate?: string;
    /**
     * Date and time when the apparel was last updated. Read-only field.
     */
    readonly updateDate?: string;
    /**
     * Name of the apparel.
     */
    apparelName: string;
    /**
     * Style of the apparel (e.g., ALE, PALE_ALE, IPA, etc.).
     */
    apparelStyle: string;
    /**
     * Universal Product Code, a 13-digit number assigned to each unique apparel product by the Federal Bar Association.
     */
    upc: string;
    /**
     * Current quantity of apparel available in stock.
     */
    quantityOnHand: number;
    /**
     * Description of the apparel.
     */
    description?: string;
    /**
     * Price of the apparel.
     */
    price: number;
};

