/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Data Transfer Object for ApparelOrderShipment entities
 */
export type ApparelOrderShipmentDto = {
    /**
     * Unique identifier for the apparel order shipment. Read-only field generated by the system.
     */
    readonly id?: number;
    /**
     * Version number for optimistic locking. Read-only field incremented on each update.
     */
    readonly version?: number;
    /**
     * Date and time when the shipment was created. Read-only field.
     */
    readonly createdDate?: string;
    /**
     * Date and time when the shipment was last updated. Read-only field.
     */
    readonly updateDate?: string;
    /**
     * Date and time when the order was shipped.
     */
    shipmentDate: string;
    /**
     * Carrier used for the shipment (e.g., FedEx, UPS, DHL).
     */
    carrier?: string;
    /**
     * Tracking number for the shipment.
     */
    trackingNumber?: string;
};

