/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Data Transfer Object for ApparelOrderLine entities
 */
export type ApparelOrderLineDto = {
    /**
     * Unique identifier for the apparel order line. Read-only field generated by the system.
     */
    readonly id?: number;
    /**
     * Version number for optimistic locking. Read-only field incremented on each update.
     */
    readonly version?: number;
    /**
     * Date and time when the apparel order line was created. Read-only field.
     */
    readonly createdDate?: string;
    /**
     * Date and time when the apparel order line was last updated. Read-only field.
     */
    readonly updateDate?: string;
    /**
     * Identifier of the apparel in this order line.
     */
    apparelId?: number;
    /**
     * Name of the apparel in this order line.
     */
    apparelName?: string;
    /**
     * Style of the apparel (e.g., ALE, PALE_ALE, IPA, etc.).
     */
    apparelStyle?: string;
    /**
     * Universal Product Code of the apparel.
     */
    upc?: string;
    /**
     * Quantity of apparel ordered.
     */
    orderQuantity: number;
    /**
     * Quantity of apparel allocated from inventory.
     */
    quantityAllocated?: number;
    /**
     * Status of the apparel order line.
     */
    status?: string;
};

