/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ApparelOrderLineDto } from './ApparelOrderLineDto';
import type { ApparelOrderShipmentDto } from './ApparelOrderShipmentDto';
/**
 * Data Transfer Object for ApparelOrder entities
 */
export type ApparelOrderDto = {
    /**
     * Unique identifier for the apparel order. Read-only field generated by the system.
     */
    readonly id?: number;
    /**
     * Version number for optimistic locking. Read-only field incremented on each update.
     */
    readonly version?: number;
    /**
     * Date and time when the apparel order was created. Read-only field.
     */
    readonly createdDate?: string;
    /**
     * Date and time when the apparel order was last updated. Read-only field.
     */
    readonly updateDate?: string;
    /**
     * Reference information from customer.
     */
    customerRef?: string;
    /**
     * Payment amount for the order.
     */
    paymentAmount: number;
    /**
     * Status of the order (e.g., NEW, PAID, CANCELLED, INPROCESS, COMPLETE).
     */
    status?: string;
    /**
     * Apparel order lines in this order.
     */
    apparelOrderLines: Array<ApparelOrderLineDto>;
    /**
     * Shipments for this order.
     */
    shipments?: Array<ApparelOrderShipmentDto>;
};

